version: '3'
services:
  web:
    container_name: my-web
    build:
      context: ./
      dockerfile: Dockerfile
    image: my-web:1.0
    ports:
      - "9088:9088"
    environment:
      ENV: dev
